include scripts/setting.mk
include scripts/tools.mk
include scripts/color.mk

# check $(NAME)
ifeq ($(findstring clean,$(MAKECMDGOALS))$(filter help,$(MAKECMDGOALS)),)
ifeq ($(NAME),conf)
SRCS := $(filter-out kconfig/mconf.c $(call find_srcs, kconfig/lxdialog), $(call find_srcs, kconfig))
INC_DIRS := ./include/ ./kconfig/
else ifeq ($(NAME),mconf)
SRCS := $(filter-out kconfig/conf.c, $(call find_srcs, kconfig))
INC_DIRS := ./include/ ./kconfig/ ./kconfig/lxdialog/
LDFLAGS += -lncursesw -ltinfo
else
$(call colored_error,$(NAME) should be either "conf" or "mconf")
endif
endif

# these files are generated by flex and bison
# - kconfig/lexer.lex.c
# - kconfig/parser.tab.c
# - kconfig/parser.tab.h
# sort is used for remove duplication when these two files are already built
SRCS := $(sort $(SRCS) kconfig/lexer.lex.c kconfig/parser.tab.c)
kconfig/lexer.lex.c: kconfig/lexer.l kconfig/parser.tab.h
	@echo + LEX $@
	flex -o $@ -L kconfig/lexer.l
kconfig/parser.tab.c kconfig/parser.tab.h: kconfig/parser.y
	@echo + YACC $@
	bison -o kconfig/parser.tab.c --defines=kconfig/parser.tab.h -t -l kconfig/parser.y

# these code even cannot pass -Werror ?!!
CFLAGS += -w

include scripts/build.mk

clean-gernerated:
	-$(RM) kconfig/lexer.lex.c
	-$(RM) kconfig/parser.tab.c
	-$(RM) kconfig/parser.tab.h
.PHONY: clean-gernerated
clean-all: clean-gernerated
